### ISSUE TITLE
The name 'tagit' already exists

### ISSUE THREAD

**Issue by onwn** [yunjae2/tagit#1]
모바일 사업자 혹은 관련분야 같긴 하지만, 어쨌든 'tagit'은 이미 존재하니,
TAGit 으로 하거나,
대소문자 구분이 효과가 없다면, tag.it혹은 ta.git 하는 식은 어떨까요?

**Comment by yunjae2** [comment]
Since the name `tagit` already exists in PyPI, we publish this project with the name of `etagit`.
